"""Add check_items to PatrolLocation

Revision ID: 6c4ef28f948e
Revises: 82693fcf8127
Create Date: 2025-12-10 10:44:42.479603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c4ef28f948e'
down_revision: Union[str, Sequence[str], None] = '82693fcf8127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patrol_locations', sa.Column('check_items', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patrol_locations', 'check_items')
    # ### end Alembic commands ###
