"""Add inspector_id to InspectionRecord

Revision ID: 8220a7569c30
Revises: b6d44abd942f
Create Date: 2025-11-26 15:36:50.588863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8220a7569c30'
down_revision: Union[str, Sequence[str], None] = 'b6d44abd942f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_records', sa.Column('inspector_id', sa.CHAR(length=36), nullable=True))
    op.create_foreign_key(None, 'inspection_records', 'users', ['inspector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspection_records', type_='foreignkey')
    op.drop_column('inspection_records', 'inspector_id')
    # ### end Alembic commands ###
