"""Add room_id to lights_out_checks

Revision ID: 82693fcf8127
Revises: f6a77ec0407d
Create Date: 2025-12-09 18:53:53.468831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '82693fcf8127'
down_revision: Union[str, Sequence[str], None] = 'f6a77ec0407d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lights_out_checks', sa.Column('room_id', sa.Integer(), nullable=True))
    op.alter_column('lights_out_checks', 'patrol_location_id',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    op.create_foreign_key(None, 'lights_out_checks', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lights_out_checks', type_='foreignkey')
    op.alter_column('lights_out_checks', 'patrol_location_id',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    op.drop_column('lights_out_checks', 'room_id')
    # ### end Alembic commands ###
